name: MYSQL backup Rclone

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  backup:
    runs-on: ubuntu-latest
    name: mysql backup

    steps:
      - uses: actions/checkout@v2
      
      - name: MYSQLdump Install
        run: |
          sudo apt-get -y update
          sudo apt-get -y install mysql-client

      - name: MYSQLdump Run
        run: |
          mkdir -p ~/mysql/db_back
          BACKUP_DST=~/mysql/db_back
          NOW=$(date +"%Y.%m.%d")
          OLD=$(date -d -5day +"%Y.%m.%d")
          mkdir -p $BACKUP_DST
          mysqldump --no-tablespaces -u ${{ secrets.DB_USER }} -h ${{ secrets.DB_HOST }} -p${{ secrets.DB_PSW }} --databases ${{ secrets.DB_NAME }} | gzip > $BACKUP_DST/${{ secrets.DB_NAME }}$NOW.sql.gz
        
      - name: Rclone Install
        run: curl https://rclone.org/install.sh | sudo bash
        
      - name: Rclone Config
        run: |
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: Rclone Run
        run: |
          rclone copy $BACKUP_DST ${{ secrets.BACKUP_DEST }} --include "${{ secrets.DB_NAME }}$NOW.sql.gz"
          rclone delete ${{ secrets.BACKUP_DEST }} --include "${{ secrets.DB_NAME }}$OLD.sql.gz"
          echo "备份完成"

